print:
	reveal-md --css dotty-is-awesome.css --title "Metaprogramming In Dotty" dotty-is-awesome.md --print dotty-is-awesome.pdf
present:
	reveal-md --css dotty-is-awesome.css --title "Metaprogramming In Dotty" dotty-is-awesome.md
